-- Your SQL goes here
CREATE TABLE equipments (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  km INTEGER NOT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  hash TEXT NOT NULL
);

CREATE TABLE persons (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  equipment_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  previous_km INTEGER NOT NULL,
  new_km INTEGER NOT NULL,
  description TEXT NOT NULL,

  FOREIGN KEY (equipment_id) REFERENCES equipments (id),
  FOREIGN KEY (person_id) REFERENCES persons (id)
);